datacenters:
  - dc_id: 1
    location: "USA"
    timezone_shift: -5
    it_ratio_weitgh: 0.494885783
    population_weight: 0.041666666667
    total_cores: 190531
    total_gpus: 1435
    total_mem: 163312
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 2
    location: "China"
    timezone_shift: 8
    it_ratio_weitgh: 0.265264578
    population_weight: 0.041666666667
    total_cores: 102127
    total_gpus: 769
    total_mem: 87537
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 3
    location: "Japan"
    timezone_shift: 9
    it_ratio_weitgh: 0.023072784
    population_weight: 0.041666666667
    total_cores: 8883
    total_gpus: 67
    total_mem: 7614
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 4
    location: "France"
    timezone_shift: 1
    it_ratio_weitgh: 0.016097291
    population_weight: 0.041666666667
    total_cores: 6197
    total_gpus: 47
    total_mem: 5312
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 5
    location: "India"
    timezone_shift: 5.5
    it_ratio_weitgh: 0.019853326
    population_weight: 0.041666666667
    total_cores: 7644
    total_gpus: 58
    total_mem: 6552
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 6
    location: "Singapore"
    timezone_shift: 8
    it_ratio_weitgh: 0.006707205
    population_weight: 0.041666666667
    total_cores: 2582
    total_gpus: 19
    total_mem: 2213
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 7
    location: "Canada"
    timezone_shift: -5
    it_ratio_weitgh: 0.025621522
    population_weight: 0.041666666667
    total_cores: 9864
    total_gpus: 74
    total_mem: 8455
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 8
    location: "Germany"
    timezone_shift: 1
    it_ratio_weitgh: 0.022536208
    population_weight: 0.041666666667
    total_cores: 8676
    total_gpus: 65
    total_mem: 7437
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 9
    location: "United_Kingdom"
    timezone_shift: 0
    it_ratio_weitgh: 0.021731343
    population_weight: 0.041666666667
    total_cores: 8367
    total_gpus: 63
    total_mem: 7171
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 10
    location: "Australia"
    timezone_shift: 10
    it_ratio_weitgh: 0.024682513
    population_weight: 0.041666666667
    total_cores: 9503
    total_gpus: 72
    total_mem: 8145
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 11
    location: "Italy"
    timezone_shift: 1
    it_ratio_weitgh: 0.007377925
    population_weight: 0.041666666667
    total_cores: 2841
    total_gpus: 21
    total_mem: 2435
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 12
    location: "South_Korea"
    timezone_shift: 9
    it_ratio_weitgh: 0.008987654
    population_weight: 0.041666666667
    total_cores: 3460
    total_gpus: 26
    total_mem: 2966
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 13
    location: "South_Africa"
    timezone_shift: 2
    it_ratio_weitgh: 0.002280450
    population_weight: 0.041666666667
    total_cores: 878
    total_gpus: 7
    total_mem: 753
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 14
    location: "Ireland"
    timezone_shift: 0
    it_ratio_weitgh: 0.004695043
    population_weight: 0.041666666667
    total_cores: 1808
    total_gpus: 14
    total_mem: 1549
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 15
    location: "UAE"
    timezone_shift: 4
    it_ratio_weitgh: 0.001207297
    population_weight: 0.041666666667
    total_cores: 465
    total_gpus: 4
    total_mem: 399
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 16
    location: "Brazil"
    timezone_shift: -3
    it_ratio_weitgh: 0.001878017
    population_weight: 0.041666666667
    total_cores: 723
    total_gpus: 5
    total_mem: 620
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 17
    location: "Israel"
    timezone_shift: 2
    it_ratio_weitgh: 0.000670720
    population_weight: 0.041666666667
    total_cores: 258
    total_gpus: 2
    total_mem: 221
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 18
    location: "Netherlands"
    timezone_shift: 1
    it_ratio_weitgh: 0.006707205
    population_weight: 0.041666666667
    total_cores: 2582
    total_gpus: 19
    total_mem: 2213
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 19
    location: "Spain"
    timezone_shift: 1
    it_ratio_weitgh: 0.007243781
    population_weight: 0.041666666667
    total_cores: 2789
    total_gpus: 21
    total_mem: 2391
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 20
    location: "Sweden"
    timezone_shift: 1
    it_ratio_weitgh: 0.004426755
    population_weight: 0.041666666667
    total_cores: 1704
    total_gpus: 13
    total_mem: 1461
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 21
    location: "Belgium"
    timezone_shift: 1
    it_ratio_weitgh: 0.000804865
    population_weight: 0.041666666667
    total_cores: 310
    total_gpus: 2
    total_mem: 266
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 22
    location: "Norway"
    timezone_shift: 1
    it_ratio_weitgh: 0.019987470
    population_weight: 0.041666666667
    total_cores: 7695
    total_gpus: 58
    total_mem: 6596
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 23
    location: "Poland"
    timezone_shift: 1
    it_ratio_weitgh: 0.006170628
    population_weight: 0.041666666667
    total_cores: 2376
    total_gpus: 18
    total_mem: 2036
    dc_config_file: "configs/dcs/dc_config.json"
  - dc_id: 24
    location: "Switzerland"
    timezone_shift: 1
    it_ratio_weitgh: 0.007109637
    population_weight: 0.041666666667
    total_cores: 2737
    total_gpus: 21
    total_mem: 2346
    dc_config_file: "configs/dcs/dc_config.json"
