datacenters:
  - dc_id: 1
    location: "US-CAL-CISO"
    timezone_shift: -7
    population_weight: 0.16
    total_cores: 50000
    total_gpus: 1000
    total_mem: 80000
    dc_config_file: "configs/dcs/dc_config.json"

  - dc_id: 2
    location: "US-TEX-ERCO"
    timezone_shift: -5
    population_weight: 0.12
    total_cores: 65000
    total_gpus: 900
    total_mem: 90000
    dc_config_file: "configs/dcs/dc_config.json"

  - dc_id: 3
    location: "US-MIDA-PJM"
    timezone_shift: -4
    population_weight: 0.14
    total_cores: 75000
    total_gpus: 800
    total_mem: 100000
    dc_config_file: "configs/dcs/dc_config.json"

  - dc_id: 4
    location: "DE-LU"
    timezone_shift: 1
    population_weight: 0.14
    total_cores: 85000
    total_gpus: 600
    total_mem: 80000
    dc_config_file: "configs/dcs/dc_config.json"

  - dc_id: 5
    location: "JP-TK"
    timezone_shift: 9
    population_weight: 0.12
    total_cores: 70000
    total_gpus: 700
    total_mem: 70000
    dc_config_file: "configs/dcs/dc_config.json"

  - dc_id: 6
    location: "SG"
    timezone_shift: 8
    population_weight: 0.10
    total_cores: 75000
    total_gpus: 700
    total_mem: 50000
    dc_config_file: "configs/dcs/dc_config.json"

  - dc_id: 7
    location: "AU-NSW"
    timezone_shift: 11
    population_weight: 0.10
    total_cores: 65000
    total_gpus: 300
    total_mem: 60000
    dc_config_file: "configs/dcs/dc_config.json"
